version: '3.1'
services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: root
      POSTGRES_DB: db
    container_name: db
    ports:
      - "5432:5432"
  test:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: root
      POSTGRES_DB: db_test
    container_name: db_test
    ports:
      - "5434:5432"